// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: mcube/examples/rpc_grpc/pb/rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_mcube_examples_rpc_grpc_pb_rpc_proto protoreflect.FileDescriptor

const file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDesc = "" +
	"\n" +
	"$mcube/examples/rpc_grpc/pb/rpc.proto\x12\x18infraboard.mcube.example\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\rGreetResponse\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2a\n" +
	"\x05Hello\x12X\n" +
	"\x05Greet\x12&.infraboard.mcube.example.GreetRequest\x1a'.infraboard.mcube.example.GreetResponseB5Z3github.com/infraboard/mcube/v2/examples/rpc_grpc/pbb\x06proto3"

var (
	file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescOnce sync.Once
	file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescData []byte
)

func file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescGZIP() []byte {
	file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescOnce.Do(func() {
		file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDesc), len(file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDesc)))
	})
	return file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDescData
}

var file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcube_examples_rpc_grpc_pb_rpc_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: infraboard.mcube.example.GreetRequest
	(*GreetResponse)(nil), // 1: infraboard.mcube.example.GreetResponse
}
var file_mcube_examples_rpc_grpc_pb_rpc_proto_depIdxs = []int32{
	0, // 0: infraboard.mcube.example.Hello.Greet:input_type -> infraboard.mcube.example.GreetRequest
	1, // 1: infraboard.mcube.example.Hello.Greet:output_type -> infraboard.mcube.example.GreetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcube_examples_rpc_grpc_pb_rpc_proto_init() }
func file_mcube_examples_rpc_grpc_pb_rpc_proto_init() {
	if File_mcube_examples_rpc_grpc_pb_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDesc), len(file_mcube_examples_rpc_grpc_pb_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcube_examples_rpc_grpc_pb_rpc_proto_goTypes,
		DependencyIndexes: file_mcube_examples_rpc_grpc_pb_rpc_proto_depIdxs,
		MessageInfos:      file_mcube_examples_rpc_grpc_pb_rpc_proto_msgTypes,
	}.Build()
	File_mcube_examples_rpc_grpc_pb_rpc_proto = out.File
	file_mcube_examples_rpc_grpc_pb_rpc_proto_goTypes = nil
	file_mcube_examples_rpc_grpc_pb_rpc_proto_depIdxs = nil
}
