// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: mcube/pb/http/entry.proto

package http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry 路由条目
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 函数名称
	// @gotags: bson:"function_name" json:"function_name"
	FunctionName string `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name" bson:"function_name"`
	// HTTP path 用于自动生成http api
	// @gotags: bson:"path" json:"path"
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path" bson:"path"`
	// HTTP method 用于自动生成http api
	// @gotags: bson:"method" json:"method"
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method" bson:"method"`
	// 资源名称
	// @gotags: bson:"resource" json:"resource"
	Resource string `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource" bson:"resource"`
	// 是否校验用户身份 (acccess_token)
	// @gotags: bson:"auth_enable" json:"auth_enable"
	AuthEnable bool `protobuf:"varint,6,opt,name=auth_enable,json=authEnable,proto3" json:"auth_enable" bson:"auth_enable"`
	// 是否校验用户权限
	// @gotags: bson:"permission_enable" json:"permission_enable"
	PermissionEnable bool `protobuf:"varint,7,opt,name=permission_enable,json=permissionEnable,proto3" json:"permission_enable" bson:"permission_enable"`
	// 允许的通过的身份标识符, 比如角色, 用户类型之类
	// @gotags: bson:"allow" json:"allow"
	Allow []string `protobuf:"bytes,12,rep,name=allow,proto3" json:"allow" bson:"allow"`
	// 是否开启操作审计, 开启后这次操作将被记录
	// @gotags: bson:"audit_log" json:"audit_log"
	AuditLog bool `protobuf:"varint,9,opt,name=audit_log,json=auditLog,proto3" json:"audit_log" bson:"audit_log"`
	// 名称空间不能为空
	// @gotags: bson:"required_namespace" json:"required_namespace"
	RequiredNamespace bool `protobuf:"varint,10,opt,name=required_namespace,json=requiredNamespace,proto3" json:"required_namespace" bson:"required_namespace"`
	// 标签
	// @gotags: bson:"labels" json:"labels"
	Labels map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"labels"`
	// 扩展属性
	// @gotags: bson:"extension" json:"extension"
	Extension     map[string]string `protobuf:"bytes,11,rep,name=extension,proto3" json:"extension" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"extension"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_mcube_pb_http_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_mcube_pb_http_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_mcube_pb_http_entry_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *Entry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Entry) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Entry) GetAuthEnable() bool {
	if x != nil {
		return x.AuthEnable
	}
	return false
}

func (x *Entry) GetPermissionEnable() bool {
	if x != nil {
		return x.PermissionEnable
	}
	return false
}

func (x *Entry) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

func (x *Entry) GetAuditLog() bool {
	if x != nil {
		return x.AuditLog
	}
	return false
}

func (x *Entry) GetRequiredNamespace() bool {
	if x != nil {
		return x.RequiredNamespace
	}
	return false
}

func (x *Entry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Entry) GetExtension() map[string]string {
	if x != nil {
		return x.Extension
	}
	return nil
}

var file_mcube_pb_http_entry_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Entry)(nil),
		Field:         20210228,
		Name:          "infraboard.mcube.http.rest_api",
		Tag:           "bytes,20210228,opt,name=rest_api",
		Filename:      "mcube/pb/http/entry.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional infraboard.mcube.http.Entry rest_api = 20210228;
	E_RestApi = &file_mcube_pb_http_entry_proto_extTypes[0]
)

var File_mcube_pb_http_entry_proto protoreflect.FileDescriptor

const file_mcube_pb_http_entry_proto_rawDesc = "" +
	"\n" +
	"\x19mcube/pb/http/entry.proto\x12\x15infraboard.mcube.http\x1a google/protobuf/descriptor.proto\"\xaa\x04\n" +
	"\x05Entry\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x1f\n" +
	"\vauth_enable\x18\x06 \x01(\bR\n" +
	"authEnable\x12+\n" +
	"\x11permission_enable\x18\a \x01(\bR\x10permissionEnable\x12\x14\n" +
	"\x05allow\x18\f \x03(\tR\x05allow\x12\x1b\n" +
	"\taudit_log\x18\t \x01(\bR\bauditLog\x12-\n" +
	"\x12required_namespace\x18\n" +
	" \x01(\bR\x11requiredNamespace\x12@\n" +
	"\x06labels\x18\b \x03(\v2(.infraboard.mcube.http.Entry.LabelsEntryR\x06labels\x12I\n" +
	"\textension\x18\v \x03(\v2+.infraboard.mcube.http.Entry.ExtensionEntryR\textension\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eExtensionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:Z\n" +
	"\brest_api\x12\x1e.google.protobuf.MethodOptions\x18\xb4\xc4\xd1\t \x01(\v2\x1c.infraboard.mcube.http.EntryR\arestApiBq\n" +
	"\x13com.google.protobufB\n" +
	"HttpProtosH\x01Z&github.com/infraboard/mcube/v2/pb/http\xf8\x01\x01\xa2\x02\x03GPB\xaa\x02\x1aGoogle.Protobuf.Reflectionb\x06proto3"

var (
	file_mcube_pb_http_entry_proto_rawDescOnce sync.Once
	file_mcube_pb_http_entry_proto_rawDescData []byte
)

func file_mcube_pb_http_entry_proto_rawDescGZIP() []byte {
	file_mcube_pb_http_entry_proto_rawDescOnce.Do(func() {
		file_mcube_pb_http_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcube_pb_http_entry_proto_rawDesc), len(file_mcube_pb_http_entry_proto_rawDesc)))
	})
	return file_mcube_pb_http_entry_proto_rawDescData
}

var file_mcube_pb_http_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mcube_pb_http_entry_proto_goTypes = []any{
	(*Entry)(nil),                      // 0: infraboard.mcube.http.Entry
	nil,                                // 1: infraboard.mcube.http.Entry.LabelsEntry
	nil,                                // 2: infraboard.mcube.http.Entry.ExtensionEntry
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_mcube_pb_http_entry_proto_depIdxs = []int32{
	1, // 0: infraboard.mcube.http.Entry.labels:type_name -> infraboard.mcube.http.Entry.LabelsEntry
	2, // 1: infraboard.mcube.http.Entry.extension:type_name -> infraboard.mcube.http.Entry.ExtensionEntry
	3, // 2: infraboard.mcube.http.rest_api:extendee -> google.protobuf.MethodOptions
	0, // 3: infraboard.mcube.http.rest_api:type_name -> infraboard.mcube.http.Entry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcube_pb_http_entry_proto_init() }
func file_mcube_pb_http_entry_proto_init() {
	if File_mcube_pb_http_entry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcube_pb_http_entry_proto_rawDesc), len(file_mcube_pb_http_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mcube_pb_http_entry_proto_goTypes,
		DependencyIndexes: file_mcube_pb_http_entry_proto_depIdxs,
		MessageInfos:      file_mcube_pb_http_entry_proto_msgTypes,
		ExtensionInfos:    file_mcube_pb_http_entry_proto_extTypes,
	}.Build()
	File_mcube_pb_http_entry_proto = out.File
	file_mcube_pb_http_entry_proto_goTypes = nil
	file_mcube_pb_http_entry_proto_depIdxs = nil
}
