// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package examples

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseGrantTypeFromString Parse GrantType from string
func ParseGrantTypeFromString(str string) (GrantType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := GrantType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown GrantType: %s", str)
	}

	return GrantType(v), nil
}

// Equal type compare
func (t GrantType) Equal(target GrantType) bool {
	return t == target
}

// IsIn todo
func (t GrantType) IsIn(targets ...GrantType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t GrantType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(t.String())
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *GrantType) UnmarshalJSON(b []byte) error {
	ins, err := ParseGrantTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
