[app]
  name = "mcube_app"
  description = ""
  encrypt_key = "defualt app encrypt key"
  cipher_prefix = "@ciphered@"

[http]
  enable = false
  host = "127.0.0.1"
  port = 8010
  path_prefix = "api"
  web_framework = ""
  read_header_timeout = 30
  read_timeout = 60
  write_timeout = 60
  idle_timeout = 300
  max_header_size = "16kb"
  enable_ssl = false
  cert_file = ""
  key_file = ""

[health_check]
  enabled = true

[cors]
  enabled = false
  cors_allowed_headers = ["*"]
  cors_allowed_origins = ["*"]
  cors_allowed_methods = ["HEAD", "OPTIONS", "GET", "POST", "PUT", "PATCH", "DELETE"]

[api_doc]
  enabled = true
  doc_path = "/apidocs.json"

[grpc]
  enable = false
  host = "127.0.0.1"
  port = 18010
  enable_ssl = false
  cert_file = ""
  key_file = ""
  enable_recovery = true
  trace = true

[trace]
  enable = false
  provider = "jaeger"
  endpoint = "http://localhost:14268/api/traces"

[metric]
  enable = false
  provider = "prometheus"
  endpoint = "/metrics"

[cache]
  # 使用换成提供方, 默认使用GoCache提供的内存缓存, 如果配置为redis 还需要配置redis的配置
  provider = "go_cache"
  # 单位秒, 默认5分钟
  ttl = 300