// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package resource

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseVISIABLE_MODEFromString Parse VISIABLE_MODE from string
func ParseVISIABLE_MODEFromString(str string) (VISIABLE_MODE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := VISIABLE_MODE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown VISIABLE_MODE: %s", str)
	}

	return VISIABLE_MODE(v), nil
}

// Equal type compare
func (t VISIABLE_MODE) Equal(target VISIABLE_MODE) bool {
	return t == target
}

// IsIn todo
func (t VISIABLE_MODE) IsIn(targets ...VISIABLE_MODE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t VISIABLE_MODE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *VISIABLE_MODE) UnmarshalJSON(b []byte) error {
	ins, err := ParseVISIABLE_MODEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
