// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package resource

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseVisiableModeFromString Parse VisiableMode from string
func ParseVisiableModeFromString(str string) (VisiableMode, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := VisiableMode_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown VisiableMode: %s", str)
	}

	return VisiableMode(v), nil
}

// Equal type compare
func (t VisiableMode) Equal(target VisiableMode) bool {
	return t == target
}

// IsIn todo
func (t VisiableMode) IsIn(targets ...VisiableMode) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t VisiableMode) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *VisiableMode) UnmarshalJSON(b []byte) error {
	ins, err := ParseVisiableModeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
