// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.6
// source: mcube/pb/resource/visiable.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VISIABLE int32

const (
	// 默认Namespace可见
	VISIABLE_NAMESPACE VISIABLE = 0
	// 域内可见
	VISIABLE_DOMAIN VISIABLE = 1
	// 全局可见
	VISIABLE_GLOBAL VISIABLE = 2
)

// Enum value maps for VISIABLE.
var (
	VISIABLE_name = map[int32]string{
		0: "NAMESPACE",
		1: "DOMAIN",
		2: "GLOBAL",
	}
	VISIABLE_value = map[string]int32{
		"NAMESPACE": 0,
		"DOMAIN":    1,
		"GLOBAL":    2,
	}
)

func (x VISIABLE) Enum() *VISIABLE {
	p := new(VISIABLE)
	*p = x
	return p
}

func (x VISIABLE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VISIABLE) Descriptor() protoreflect.EnumDescriptor {
	return file_mcube_pb_resource_visiable_proto_enumTypes[0].Descriptor()
}

func (VISIABLE) Type() protoreflect.EnumType {
	return &file_mcube_pb_resource_visiable_proto_enumTypes[0]
}

func (x VISIABLE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VISIABLE.Descriptor instead.
func (VISIABLE) EnumDescriptor() ([]byte, []int) {
	return file_mcube_pb_resource_visiable_proto_rawDescGZIP(), []int{0}
}

var File_mcube_pb_resource_visiable_proto protoreflect.FileDescriptor

var file_mcube_pb_resource_visiable_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x19, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6d,
	0x63, 0x75, 0x62, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2a, 0x31, 0x0a,
	0x08, 0x56, 0x49, 0x53, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x41, 0x4d,
	0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x4d, 0x41,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4c, 0x4f, 0x42, 0x41, 0x4c, 0x10, 0x02,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2f,
	0x70, 0x62, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mcube_pb_resource_visiable_proto_rawDescOnce sync.Once
	file_mcube_pb_resource_visiable_proto_rawDescData = file_mcube_pb_resource_visiable_proto_rawDesc
)

func file_mcube_pb_resource_visiable_proto_rawDescGZIP() []byte {
	file_mcube_pb_resource_visiable_proto_rawDescOnce.Do(func() {
		file_mcube_pb_resource_visiable_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcube_pb_resource_visiable_proto_rawDescData)
	})
	return file_mcube_pb_resource_visiable_proto_rawDescData
}

var file_mcube_pb_resource_visiable_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcube_pb_resource_visiable_proto_goTypes = []interface{}{
	(VISIABLE)(0), // 0: infraboard.mcube.resource.VISIABLE
}
var file_mcube_pb_resource_visiable_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcube_pb_resource_visiable_proto_init() }
func file_mcube_pb_resource_visiable_proto_init() {
	if File_mcube_pb_resource_visiable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcube_pb_resource_visiable_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcube_pb_resource_visiable_proto_goTypes,
		DependencyIndexes: file_mcube_pb_resource_visiable_proto_depIdxs,
		EnumInfos:         file_mcube_pb_resource_visiable_proto_enumTypes,
	}.Build()
	File_mcube_pb_resource_visiable_proto = out.File
	file_mcube_pb_resource_visiable_proto_rawDesc = nil
	file_mcube_pb_resource_visiable_proto_goTypes = nil
	file_mcube_pb_resource_visiable_proto_depIdxs = nil
}
