// Code generated by protoc-gen-go-http. DO NOT EDIT.

package http

import (
	router "github.com/infraboard/mcube/http/router"
)

// HttpEntry todo
func HttpEntry() *router.EntrySet {
	set := &router.EntrySet{
		Items: []*router.Entry{
			{
				GrpcPath:     "/mcube.example.hello.HelloService/Hello",
				FunctionName: "Hello",
			},
			{
				GrpcPath:         "/mcube.example.hello.HelloService/Hello2",
				FunctionName:     "Hello2",
				Path:             "/hello/:value",
				Method:           "GET",
				Resource:         "Hello",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "list"},
			},
		},
	}
	return set
}
