// Code generated by protoc-gen-go-http. DO NOT EDIT.

package http

import (
	router "github.com/infraboard/mcube/http/router"
)

// HttpEntry todo
func HttpEntry() *router.EntrySet {
	set := &router.EntrySet{
		Items: []*router.Entry{
			{
				Path:             "/mcube.example.hello.HelloService/Hello",
				Method:           "GET",
				FunctionName:     "Hello",
				Resource:         "Hello",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "get"},
			},
			{
				Path:             "/mcube.example.hello.HelloService/Hello2",
				Method:           "GET",
				FunctionName:     "Hello2",
				Resource:         "Hello",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "list"},
			},
		},
	}
	return set
}
