// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: mcube/pb/request/request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMode int32

const (
	UpdateMode_PUT   UpdateMode = 0
	UpdateMode_PATCH UpdateMode = 1
)

// Enum value maps for UpdateMode.
var (
	UpdateMode_name = map[int32]string{
		0: "PUT",
		1: "PATCH",
	}
	UpdateMode_value = map[string]int32{
		"PUT":   0,
		"PATCH": 1,
	}
)

func (x UpdateMode) Enum() *UpdateMode {
	p := new(UpdateMode)
	*p = x
	return p
}

func (x UpdateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_mcube_pb_request_request_proto_enumTypes[0].Descriptor()
}

func (UpdateMode) Type() protoreflect.EnumType {
	return &file_mcube_pb_request_request_proto_enumTypes[0]
}

func (x UpdateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateMode.Descriptor instead.
func (UpdateMode) EnumDescriptor() ([]byte, []int) {
	return file_mcube_pb_request_request_proto_rawDescGZIP(), []int{0}
}

var File_mcube_pb_request_request_proto protoreflect.FileDescriptor

const file_mcube_pb_request_request_proto_rawDesc = "" +
	"\n" +
	"\x1emcube/pb/request/request.proto\x12\x18infraboard.mcube.request* \n" +
	"\n" +
	"UpdateMode\x12\a\n" +
	"\x03PUT\x10\x00\x12\t\n" +
	"\x05PATCH\x10\x01B+Z)github.com/infraboard/mcube/v2/pb/requestb\x06proto3"

var (
	file_mcube_pb_request_request_proto_rawDescOnce sync.Once
	file_mcube_pb_request_request_proto_rawDescData []byte
)

func file_mcube_pb_request_request_proto_rawDescGZIP() []byte {
	file_mcube_pb_request_request_proto_rawDescOnce.Do(func() {
		file_mcube_pb_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcube_pb_request_request_proto_rawDesc), len(file_mcube_pb_request_request_proto_rawDesc)))
	})
	return file_mcube_pb_request_request_proto_rawDescData
}

var file_mcube_pb_request_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcube_pb_request_request_proto_goTypes = []any{
	(UpdateMode)(0), // 0: infraboard.mcube.request.UpdateMode
}
var file_mcube_pb_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcube_pb_request_request_proto_init() }
func file_mcube_pb_request_request_proto_init() {
	if File_mcube_pb_request_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcube_pb_request_request_proto_rawDesc), len(file_mcube_pb_request_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcube_pb_request_request_proto_goTypes,
		DependencyIndexes: file_mcube_pb_request_request_proto_depIdxs,
		EnumInfos:         file_mcube_pb_request_request_proto_enumTypes,
	}.Build()
	File_mcube_pb_request_request_proto = out.File
	file_mcube_pb_request_request_proto_goTypes = nil
	file_mcube_pb_request_request_proto_depIdxs = nil
}
