// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: mcube/pb/response/response.proto

package response

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response to be used by controllers.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 自定义返回码  0:表示正常
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 数据类型, 可以缺省
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// 异常的范围
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// 异常原因
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// 关于这次响应的说明信息
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// 数据meta
	Meta map[string]string `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// data 具体的数据
	Data          *anypb.Any `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_mcube_pb_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mcube_pb_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mcube_pb_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Response) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Response) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Response) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mcube_pb_response_response_proto protoreflect.FileDescriptor

const file_mcube_pb_response_response_proto_rawDesc = "" +
	"\n" +
	" mcube/pb/response/response.proto\x12\x19infraboard.mcube.response\x1a\x19google/protobuf/any.proto\"\xa8\x02\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12A\n" +
	"\x04meta\x18\x06 \x03(\v2-.infraboard.mcube.response.Response.MetaEntryR\x04meta\x12(\n" +
	"\x04data\x18\a \x01(\v2\x14.google.protobuf.AnyR\x04data\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*github.com/infraboard/mcube/v2/pb/responseb\x06proto3"

var (
	file_mcube_pb_response_response_proto_rawDescOnce sync.Once
	file_mcube_pb_response_response_proto_rawDescData []byte
)

func file_mcube_pb_response_response_proto_rawDescGZIP() []byte {
	file_mcube_pb_response_response_proto_rawDescOnce.Do(func() {
		file_mcube_pb_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcube_pb_response_response_proto_rawDesc), len(file_mcube_pb_response_response_proto_rawDesc)))
	})
	return file_mcube_pb_response_response_proto_rawDescData
}

var file_mcube_pb_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcube_pb_response_response_proto_goTypes = []any{
	(*Response)(nil),  // 0: infraboard.mcube.response.Response
	nil,               // 1: infraboard.mcube.response.Response.MetaEntry
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_mcube_pb_response_response_proto_depIdxs = []int32{
	1, // 0: infraboard.mcube.response.Response.meta:type_name -> infraboard.mcube.response.Response.MetaEntry
	2, // 1: infraboard.mcube.response.Response.data:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcube_pb_response_response_proto_init() }
func file_mcube_pb_response_response_proto_init() {
	if File_mcube_pb_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcube_pb_response_response_proto_rawDesc), len(file_mcube_pb_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcube_pb_response_response_proto_goTypes,
		DependencyIndexes: file_mcube_pb_response_response_proto_depIdxs,
		MessageInfos:      file_mcube_pb_response_response_proto_msgTypes,
	}.Build()
	File_mcube_pb_response_response_proto = out.File
	file_mcube_pb_response_response_proto_goTypes = nil
	file_mcube_pb_response_response_proto_depIdxs = nil
}
