//go:generate  mcube enum -m -p
//
// Code generated by protoc-gen-go-ext. DO NOT EDIT.
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pb/event/level.proto

package event

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Level int32

const (
	Level_Trace    Level = 0
	Level_Debug    Level = 1
	Level_Info     Level = 2
	Level_Warn     Level = 3
	Level_Error    Level = 4
	Level_Critical Level = 5
	Level_Disaster Level = 6
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "Trace",
		1: "Debug",
		2: "Info",
		3: "Warn",
		4: "Error",
		5: "Critical",
		6: "Disaster",
	}
	Level_value = map[string]int32{
		"Trace":    0,
		"Debug":    1,
		"Info":     2,
		"Warn":     3,
		"Error":    4,
		"Critical": 5,
		"Disaster": 6,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_event_level_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_pb_event_level_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_pb_event_level_proto_rawDescGZIP(), []int{0}
}

var File_pb_event_level_proto protoreflect.FileDescriptor

var file_pb_event_level_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2a, 0x58, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x72, 0x61, 0x63, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x57, 0x61, 0x72, 0x6e, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x10, 0x05, 0x12,
	0x0c, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x61, 0x73, 0x74, 0x65, 0x72, 0x10, 0x06, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6d, 0x63, 0x75, 0x62, 0x65, 0x2f, 0x62, 0x75, 0x73,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_event_level_proto_rawDescOnce sync.Once
	file_pb_event_level_proto_rawDescData = file_pb_event_level_proto_rawDesc
)

func file_pb_event_level_proto_rawDescGZIP() []byte {
	file_pb_event_level_proto_rawDescOnce.Do(func() {
		file_pb_event_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_event_level_proto_rawDescData)
	})
	return file_pb_event_level_proto_rawDescData
}

var file_pb_event_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_event_level_proto_goTypes = []interface{}{
	(Level)(0), // 0: mcube.event.Level
}
var file_pb_event_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_event_level_proto_init() }
func file_pb_event_level_proto_init() {
	if File_pb_event_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_event_level_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_event_level_proto_goTypes,
		DependencyIndexes: file_pb_event_level_proto_depIdxs,
		EnumInfos:         file_pb_event_level_proto_enumTypes,
	}.Build()
	File_pb_event_level_proto = out.File
	file_pb_event_level_proto_rawDesc = nil
	file_pb_event_level_proto_goTypes = nil
	file_pb_event_level_proto_depIdxs = nil
}
